#!/usr/bin/env node
/**
 * build-data.mjs
 * Aggregates every per-center JSON file in /data/centers into a single
 * /public/data/centers.json array that the static site fetches, and copies the
 * tag vocabulary to /public/data/tags.json. It also lightly validates each entry
 * against the required fields in schema/entry.schema.json.
 *
 * Run:  node scripts/build-data.mjs
 * This is the Cloudflare Pages "build command".
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const centersDir = join(root, "data", "centers");
const outDir = join(root, "public", "data");
const schema = JSON.parse(readFileSync(join(root, "schema", "entry.schema.json"), "utf8"));
const tags = JSON.parse(readFileSync(join(root, "schema", "tags.json"), "utf8"));

const validTagIds = new Set(tags.groups.flatMap((g) => g.tags.map((t) => t.id)));
const required = schema.required;

mkdirSync(outDir, { recursive: true });

const files = readdirSync(centersDir).filter((f) => f.endsWith(".json"));
const centers = [];
const problems = [];

for (const file of files) {
  const entry = JSON.parse(readFileSync(join(centersDir, file), "utf8"));

  for (const key of required) {
    if (!(key in entry)) problems.push(`${file}: missing required field "${key}"`);
  }
  for (const t of entry.tags ?? []) {
    if (!validTagIds.has(t)) problems.push(`${file}: unknown tag "${t}" (not in schema/tags.json)`);
  }
  centers.push(entry);
}

// De-dupe by id. The dev filesystem this repo is often edited from returns EPERM on
// unlink, so stale/duplicate files in data/centers can't always be deleted in place
// (see deletions.txt) -- collapse duplicate ids here so the published site never shows
// the same center twice even if two files on disk share an id.
const dupeNotes = [];
const seen = new Set();
const deduped = [];
for (const c of centers) {
  if (c.id) {
    if (seen.has(c.id)) {
      dupeNotes.push(`duplicate id "${c.id}" -- kept first occurrence, see deletions.txt`);
      continue;
    }
    seen.add(c.id);
  }
  deduped.push(c);
}
centers.length = 0;
centers.push(...deduped);

// Deterministic order: by region then name.
centers.sort(
  (a, b) =>
    (a.location?.region ?? "").localeCompare(b.location?.region ?? "") ||
    a.name.localeCompare(b.name)
);

if (problems.length) {
  console.error("Data validation problems:\n  " + problems.join("\n  "));
  process.exit(1);
}

writeFileSync(join(outDir, "centers.json"), JSON.stringify(centers, null, 2));
writeFileSync(join(outDir, "tags.json"), JSON.stringify(tags, null, 2));

// Also emit a plain-JS bundle that assigns globals so index.html works when
// simply double-clicked (file://), where fetch() of local JSON is blocked.
const dataJs =
  `// Auto-generated by scripts/build-data.mjs - do not edit by hand.\n` +
  `window.__CENTERS__ = ${JSON.stringify(centers)};\n` +
  `window.__TAGS__ = ${JSON.stringify(tags)};\n`;
writeFileSync(join(outDir, "data.js"), dataJs);

if (dupeNotes.length) console.log("  " + dupeNotes.join("\n  "));
console.log(`Built ${centers.length} center(s) -> public/data/centers.json + data.js`);
